
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 62773:52773
      - 63773
    volumes:
      - ./:/home/irisowner/dev
  
  test-ui:
    build:
      context: ./testing-dashboard-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
        - 4000:3000